const todayIso = () => new Date().toISOString();
const todayDate = () => todayIso().slice(0, 10);

const buildPlatformSeed = () => ({
  users: [
    {
      _id: 'seed_admin_1',
      name: 'Demo Admin',
      email: 'admin@edumaster.local',
      passwordPlain: 'Admin@123',
      role: 'admin',
      device: 'web',
      session: null,
      streak: 12,
      points: 480,
      badges: [{ code: 'mentor_mode', label: 'Mentor Mode' }],
      referral_code: 'ADMIN12',
      created_at: todayIso(),
    },
    {
      _id: 'seed_student_1',
      name: 'Aarav Singh',
      email: 'student@edumaster.local',
      passwordPlain: 'Student@123',
      role: 'student',
      device: 'android',
      session: null,
      streak: 9,
      points: 265,
      badges: [{ code: 'consistency', label: 'Consistency Champ' }],
      referral_code: 'AARAV9',
      created_at: todayIso(),
    },
  ],
  courses: [
    {
      _id: 'course_ssc_je_ee_2026',
      title: 'SSC JE 2026 Electrical Power Track',
      description: 'Complete SSC JE Electrical batch with recorded lessons, premium notes, PYQ drills, and weekly mentorship.',
      category: 'SSC JE',
      exam: 'SSC JE',
      subject: 'Electrical Engineering',
      level: 'Full Course',
      price: 3999,
      validityDays: 365,
      thumbnailUrl: 'https://picsum.photos/seed/ssc-je-ee/900/600',
      instructor: 'Er. P. K. Narang',
      officialChannelUrl: 'https://www.youtube.com/@btechmadeeasy',
      createdBy: 'seed_admin_1',
      modules: [
        {
          id: 'mod_networks',
          title: 'Network Theory',
          lessons: [
            {
              id: 'lesson_network_1',
              title: 'Circuits & Network Reduction Essentials',
              type: 'youtube',
              durationMinutes: 34,
              videoUrl: 'https://www.youtube.com/watch?v=4MpvZQDwzZ8&list=PLU9qGTRXUDkliZ0JI2dTJ8YFnEm8c9Sya',
              notesUrl: 'https://example.com/notes/network-theory-1.pdf',
              premium: false,
            },
            {
              id: 'lesson_network_2',
              title: 'Thevenin, Norton and Maximum Power Transfer',
              type: 'youtube',
              durationMinutes: 48,
              videoUrl: 'https://www.youtube.com/watch?v=sfeLBPkY95g',
              notesUrl: 'https://example.com/notes/network-theory-2.pdf',
              premium: true,
            },
          ],
        },
        {
          id: 'mod_power_systems',
          title: 'Power Systems',
          lessons: [
            {
              id: 'lesson_power_1',
              title: 'Power Systems Overview',
              type: 'youtube',
              durationMinutes: 42,
              videoUrl: 'https://www.youtube.com/watch?v=Ua3LKJLmrI0',
              notesUrl: 'https://example.com/notes/power-system-1.pdf',
              premium: true,
            },
            {
              id: 'lesson_power_2',
              title: 'Load Flow Analysis for Competitive Exams',
              type: 'youtube',
              durationMinutes: 56,
              videoUrl: 'https://www.youtube.com/watch?v=U0fxF9rGa-E',
              notesUrl: 'https://example.com/notes/power-system-2.pdf',
              premium: true,
            },
          ],
        },
      ],
      created_at: todayIso(),
    },
    {
      _id: 'course_rrb_je_civil_2026',
      title: 'RRB JE Civil Fast Track',
      description: 'Mobile-first civil engineering roadmap with concept videos, PDF notes, live revision classes, and practice sets.',
      category: 'RRB JE',
      exam: 'RRB JE',
      subject: 'Civil Engineering',
      level: 'Fast Track',
      price: 2999,
      validityDays: 240,
      thumbnailUrl: 'https://picsum.photos/seed/rrb-je-civil/900/600',
      instructor: 'Er. Amit Verma',
      officialChannelUrl: 'https://www.youtube.com/@engineeringfunda',
      createdBy: 'seed_admin_1',
      modules: [
        {
          id: 'mod_surveying',
          title: 'Surveying',
          lessons: [
            {
              id: 'lesson_survey_1',
              title: 'Basics of Surveying for SSC JE / RRB JE',
              type: 'youtube',
              durationMinutes: 26,
              videoUrl: 'https://www.youtube.com/watch?v=1BOynNNCx_s',
              notesUrl: 'https://example.com/notes/surveying-1.pdf',
              premium: false,
            },
            {
              id: 'lesson_survey_2',
              title: 'Contour Maps and Surveying Revision',
              type: 'youtube',
              durationMinutes: 39,
              videoUrl: 'https://www.youtube.com/watch?v=SuJvK7j6mRo',
              notesUrl: 'https://example.com/notes/surveying-2.pdf',
              premium: true,
            },
          ],
        },
      ],
      created_at: todayIso(),
    },
    {
      _id: 'course_ssc_ga_revision',
      title: 'SSC JE General Awareness Revision Vault',
      description: 'Daily current affairs capsules, one-page notes, and live revision sprints for GA scoring.',
      category: 'General Awareness',
      exam: 'SSC JE / RRB JE',
      subject: 'General Awareness',
      level: 'Revision Pack',
      price: 999,
      validityDays: 120,
      thumbnailUrl: 'https://picsum.photos/seed/ga-revision/900/600',
      instructor: 'Ananya Rao',
      officialChannelUrl: 'https://www.youtube.com/@SSCAdda247',
      createdBy: 'seed_admin_1',
      modules: [
        {
          id: 'mod_ga_daily',
          title: 'Daily Capsules',
          lessons: [
            {
              id: 'lesson_ga_1',
              title: 'CM and Governors 2025 Revision',
              type: 'youtube',
              durationMinutes: 18,
              videoUrl: 'https://www.youtube.com/watch?v=shvvsjN4ULo',
              notesUrl: 'https://example.com/notes/ga-budget.pdf',
              premium: false,
            },
            {
              id: 'lesson_ga_2',
              title: 'Current Affairs Today for SSC & Railway',
              type: 'youtube',
              durationMinutes: 22,
              videoUrl: 'https://www.youtube.com/watch?v=xYw5io8zgpE',
              notesUrl: 'https://example.com/notes/ga-current-affairs.pdf',
              premium: false,
            },
          ],
        },
      ],
      created_at: todayIso(),
    },
  ],
  tests: [
    {
      _id: 'test_ssc_full_01',
      title: 'SSC JE Full-Length Mock 01',
      description: '180 questions across technical, reasoning, and general awareness with exam-level time pressure.',
      category: 'SSC JE',
      type: 'full-length',
      durationMinutes: 120,
      totalMarks: 180,
      negativeMarking: 0.25,
      course: 'course_ssc_je_ee_2026',
      sectionBreakup: [
        { name: 'Technical', questions: 120 },
        { name: 'General Intelligence', questions: 30 },
        { name: 'General Awareness', questions: 30 },
      ],
      questions: [
        {
          id: 'q_full_1',
          questionText: 'Thevenin equivalent of a linear bilateral network is represented by?',
          options: ['Current source only', 'Voltage source in series with resistance', 'Capacitor only', 'Dependent source only'],
          correctOption: 1,
          answer: 1,
          explanation: 'Thevenin theorem reduces the network to an equivalent voltage source with a series resistance.',
          marks: 1,
          topic: 'Network Theory',
        },
        {
          id: 'q_full_2',
          questionText: 'For a purely inductive circuit, current lags voltage by:',
          options: ['0°', '45°', '90°', '180°'],
          correctOption: 2,
          answer: 2,
          explanation: 'In an ideal inductive circuit current lags voltage by 90 degrees.',
          marks: 1,
          topic: 'Basic Electrical Engineering',
        },
        {
          id: 'q_full_3',
          questionText: 'Which article of the Indian Constitution abolishes untouchability?',
          options: ['Article 14', 'Article 17', 'Article 19', 'Article 32'],
          correctOption: 1,
          answer: 1,
          explanation: 'Article 17 explicitly abolishes untouchability.',
          marks: 1,
          topic: 'General Awareness',
        },
      ],
      created_at: todayIso(),
    },
    {
      _id: 'test_rrb_topic_strength',
      title: 'RRB JE Surveying Topic Test',
      description: 'Topic-wise test focused on surveying accuracy, speed, and explanation-based revision.',
      category: 'RRB JE',
      type: 'topic-wise',
      durationMinutes: 35,
      totalMarks: 50,
      negativeMarking: 0.33,
      course: 'course_rrb_je_civil_2026',
      sectionBreakup: [{ name: 'Surveying', questions: 25 }],
      questions: [
        {
          id: 'q_topic_1',
          questionText: 'Contour lines never:',
          options: ['Intersect each other', 'Represent equal elevation', 'Help identify slopes', 'Form closed loops'],
          correctOption: 0,
          answer: 0,
          explanation: 'Contour lines for different elevations do not intersect in normal terrain.',
          marks: 2,
          topic: 'Surveying',
        },
        {
          id: 'q_topic_2',
          questionText: 'The reduced level of a point is measured with reference to:',
          options: ['Magnetic north', 'Benchmark', 'Latitude', 'Bearing'],
          correctOption: 1,
          answer: 1,
          explanation: 'Reduced level is always determined relative to a benchmark or assumed datum.',
          marks: 2,
          topic: 'Surveying',
        },
      ],
      created_at: todayIso(),
    },
  ],
  quiz: {
    _id: 'quiz_daily_today',
    date: todayDate(),
    questions: [
      {
        id: 'quiz_q1',
        prompt: 'The SI unit of magnetic flux is:',
        options: ['Weber', 'Tesla', 'Henry', 'Farad'],
        answer: 'Weber',
        explanation: 'Magnetic flux is measured in weber.',
        topic: 'Electrical Machines',
      },
      {
        id: 'quiz_q2',
        prompt: 'Who is known as the Father of the Indian Constitution?',
        options: ['Dr. B. R. Ambedkar', 'Rajendra Prasad', 'Jawaharlal Nehru', 'Sardar Patel'],
        answer: 'Dr. B. R. Ambedkar',
        explanation: 'Dr. B. R. Ambedkar chaired the Drafting Committee.',
        topic: 'Polity',
      },
      {
        id: 'quiz_q3',
        prompt: 'Specific gravity of cement is approximately:',
        options: ['1.15', '2.25', '3.15', '4.15'],
        answer: '3.15',
        explanation: 'The typical specific gravity of cement is 3.15.',
        topic: 'Building Materials',
      },
      {
        id: 'quiz_q4',
        prompt: 'The frequency of AC supply in India is:',
        options: ['25 Hz', '40 Hz', '50 Hz', '60 Hz'],
        answer: '50 Hz',
        explanation: 'India standard AC supply frequency is 50 Hz.',
        topic: 'Power Systems',
      },
      {
        id: 'quiz_q5',
        prompt: 'Which gas is used in electric bulbs to reduce filament evaporation?',
        options: ['Oxygen', 'Nitrogen', 'Argon', 'Hydrogen'],
        answer: 'Argon',
        explanation: 'Argon is commonly filled inside incandescent bulbs.',
        topic: 'Basic Electrical Engineering',
      },
    ],
  },
  liveClasses: [
    {
      _id: 'live_class_1',
      title: 'Power Systems Live Marathon',
      instructor: 'Er. P. K. Narang',
      startTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      durationMinutes: 90,
      provider: 'Zoom',
      mode: 'live',
      roomUrl: 'https://zoom.us/j/sscjepower',
      recordingUrl: 'https://recordings.edumaster.local/power-systems-marathon',
      chatEnabled: true,
      doubtSolving: true,
      replayAvailable: true,
      attendees: 842,
      topicTags: ['Power Systems', 'SSC JE'],
    },
    {
      _id: 'live_class_2',
      title: 'RRB JE Civil Doubt Clinic',
      instructor: 'Er. Amit Verma',
      startTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
      durationMinutes: 60,
      provider: 'Agora',
      mode: 'live',
      roomUrl: 'https://app.edumaster.local/live/rrb-civil-doubt-clinic',
      recordingUrl: 'https://recordings.edumaster.local/rrb-civil-doubt-clinic',
      chatEnabled: true,
      doubtSolving: true,
      replayAvailable: true,
      attendees: 566,
      topicTags: ['Surveying', 'RRB JE'],
    },
    {
      _id: 'live_replay_1',
      title: 'Weekly General Awareness Replay',
      instructor: 'Ananya Rao',
      startTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      durationMinutes: 55,
      provider: 'Recording',
      mode: 'replay',
      roomUrl: null,
      recordingUrl: 'https://recordings.edumaster.local/ga-weekly-replay',
      chatEnabled: false,
      doubtSolving: false,
      replayAvailable: true,
      attendees: 1210,
      topicTags: ['General Awareness'],
    },
  ],
  subscriptions: [
    {
      _id: 'plan_testbook_pass',
      title: 'EduMaster Pass',
      description: 'Unlimited access to mock tests, daily quizzes, premium lessons, live classes, and AI recommendations.',
      price: 1499,
      billingCycle: 'monthly',
      accessType: 'subscription',
      features: ['Unlimited mock tests', 'All premium lessons', 'Daily quiz streak rewards', 'Live class recordings'],
    },
    {
      _id: 'plan_je_pro',
      title: 'JE Pro Annual',
      description: 'Best for serious aspirants preparing for SSC JE and RRB JE with full-length tests and mentorship.',
      price: 8999,
      billingCycle: 'yearly',
      accessType: 'subscription',
      features: ['12 months validity', 'All India rank', 'Priority doubt solving', '1:1 strategy sessions'],
    },
  ],
  notifications: [
    {
      _id: 'notif_seed_1',
      userId: 'seed_student_1',
      title: 'Daily quiz is live',
      message: 'Attempt today’s 5-question quiz before midnight to protect your streak.',
      type: 'quiz-reminder',
      createdAt: todayIso(),
    },
    {
      _id: 'notif_seed_2',
      userId: 'seed_student_1',
      title: 'Live class starts in 2 hours',
      message: 'Power Systems Live Marathon begins soon. Tap in early to ask doubts.',
      type: 'live-class',
      createdAt: todayIso(),
    },
  ],
  enrollments: [
    {
      _id: 'enrollment_seed_1',
      userId: 'seed_student_1',
      courseId: 'course_ssc_je_ee_2026',
      accessType: 'course',
      source: 'payment',
      enrolledAt: todayIso(),
      expiresAt: new Date(Date.now() + 320 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
  watchHistory: [
    {
      _id: 'watch_seed_1',
      userId: 'seed_student_1',
      courseId: 'course_ssc_je_ee_2026',
      lessonId: 'lesson_network_2',
      progressPercent: 62,
      progressSeconds: 1780,
      completed: false,
      updatedAt: todayIso(),
    },
  ],
  testAttempts: [
    {
      _id: 'attempt_seed_1',
      userId: 'seed_student_1',
      testId: 'test_ssc_full_01',
      score: 124,
      totalMarks: 180,
      correctCount: 132,
      incorrectCount: 32,
      unattemptedCount: 16,
      percentile: 87.45,
      rank: 142,
      answers: {
        q_full_1: 1,
        q_full_2: 1,
        q_full_3: 1,
      },
      weakTopics: ['Network Theory'],
      strongTopics: ['General Awareness'],
      solutions: [
        {
          questionId: 'q_full_1',
          questionText: 'Thevenin equivalent of a linear bilateral network is represented by?',
          selectedOption: 1,
          correctOption: 1,
          explanation: 'Thevenin theorem reduces the network to an equivalent voltage source with a series resistance.',
          topic: 'Network Theory',
        },
      ],
      startedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
      completedAt: new Date(Date.now() - 34 * 60 * 60 * 1000).toISOString(),
    },
  ],
  liveChatMessages: [
    {
      _id: 'live_chat_seed_1',
      liveClassId: 'live_class_1',
      userId: 'seed_student_1',
      userName: 'Aarav Singh',
      kind: 'chat',
      message: 'Will you cover load flow shortcuts in today’s session?',
      createdAt: todayIso(),
    },
    {
      _id: 'live_chat_seed_2',
      liveClassId: 'live_class_1',
      userId: 'seed_admin_1',
      userName: 'Demo Admin',
      kind: 'doubt',
      message: 'Yes, load flow and fault analysis are both scheduled in the second half.',
      createdAt: todayIso(),
    },
  ],
  userSubscriptions: [
    {
      _id: 'user_subscription_seed_1',
      userId: 'seed_student_1',
      planId: 'plan_testbook_pass',
      status: 'active',
      source: 'payment',
      startedAt: todayIso(),
      expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
});

module.exports = {
  buildPlatformSeed,
};
